export const Data = [
    {
      id: 1,
      url: "/Users/forteacher.jpeg",
      title: "For Teachers",
      headline: "Teaching Made Effortless with MINTRIX",
      subheadline: "Focus on your students, not on the paperwork.",
      content: [
        "Instantly access timetables, schedules, and classroom rosters.",
        "AI-generated student performance insights at your fingertips.",
        "Streamlined communication with parents and administrators.",
        "Plan lessons and track assignments with AI-powered tools.",
      ],
      cta: "Explore Teacher Solutions",
    },
    {
      id: 2,
      url: "/Users/forstudent.png",
      title: "For Students",
      headline: "Learn Smarter, Not Harder.",
      subheadline: "Personalized support for every step of your academic journey.",
      content: [
        "AI-powered reminders for assignments, exams, and activities.",
        "Real-time performance updates and learning recommendations.",
        "Seamless access to school announcements and event calendars.",
        "Direct communication with teachers and administrators via chatbot.",
      ],
      cta: "See How Students Benefit",
    },
    {
      id: 3,
      url: "/Users/forstaff.png",
      title: "For Faculty & Staff",
      headline: "Simplify School Operations, Effortlessly.",
      subheadline: "Let AI handle the busywork while you focus on impact.",
      content: [
        "Automated fee collection and real-time financial tracking.",
        "Effortless timetable scheduling and conflict resolution.",
        "Easy communication with teachers, students, and parents.",
        "Streamlined record-keeping for attendance, grades, and compliance.",
      ],
      cta: "Discover Operational Excellence",
    },
    {
      id: 4,
      url: "/Users/forparents.png",
      title: "For Parents",
      headline: "Stay Connected to Your Child’s Journey.",
      subheadline: "Real-time updates, insights, and communication at your fingertips.",
      content: [
        "Receive instant notifications about fees, attendance, and grades.",
        "Chat directly with teachers or the school via the AI chatbot.",
        "Track upcoming events, holidays, and school updates.",
        "Personalized insights into your child’s academic progress.",
      ],
      cta: "Experience Seamless Parent Communication",
    },
    {
      id: 5,
      url: "/Users/forinquiries.png",
      title: "For Inquiries & Marketing",
      headline: "Your School’s Personal Assistant for Every Inquiry.",
      subheadline: "Let AI bots handle inquiries, so your staff doesn’t have to.",
      content: [
        "Respond to admissions inquiries 24/7 with personalized answers.",
        "Provide details on school facilities, courses, and policies instantly.",
        "Capture leads from prospective students and parents automatically.",
        "Streamline internal marketing campaigns with AI-driven analytics.",
      ],
      cta: "Learn More About Smart Inquiries",
    },
  ];
  